#!/usr/bin/env bash
# Install and configure HAproxy on your load balancer server

sudo apt-get -y update
sudo apt-get install -y haproxy
config=\
"
frontend  web-frontend
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 210092-web-01 34.207.83.202:80 check
        server 210092-web-02 100.25.171.33:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
