#!/usr/bin/env bash

# This script display the  listening ports available
# That only shows listening sockets
# That shows the PID and name of the program to which each socket belongs

# netstat --listening --program
# OR
# netstat -lp
# OR
netstat -ltup
