#!/usr/bin/env bash
# Sscript displays list of currently running processes.
# Must show all processes, for all users, including those which might not have a TTY
# Displays in a user-oriented format
# Show process hierarchy too

ps -auxf
