#!/usr/bin/env bash
# display the PID, along with the process name, of processes
# first: the  bash PID
# second: script (3-show_your_bash_pid_made_easy) PID
# whose name contain the word bash

pgrep -l bash
