#!/usr/bin/env bash
# Script to stop or terminate 4-to_infinity_and_beyond process.
# without applying "kill or killall"

# pkill -15 "bash ./4-to_infinity_and_beyond" -f

# OR

pkill -f "4-to_infinity_and_beyond"
