#!/usr/bin/env bash
# Configure an Nginx server as an  nginx user listening on port 8080.

# set user in the config by replacing '#user' and it's value
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# replace port 80 with 8080 in the sites-available config
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# change ownership permissions to read/write to the config file
chmod 644 /etc/nginx/nginx.conf
# An apache server can interfere with the nginx so kill the process if it is running
pkill apache2
#start nginx services
sudo -u nginx service nginx start
